### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#10]
Hi!  I took the .zip file in your releases, and expanded it, and put the .dll file into the plugins folder.  However, this is the error when jellyfin starts:

```
18:31:44] [INF] [1] App: Loaded assembly Jellyfin.Plugin.PhoenixAdult, Version=2.0.1.26, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Jellyfin.Plugin.PhoenixAdult.dll
[18:31:44] [ERR] [1] App: Error getting exported types from Jellyfin.Plugin.PhoenixAdult, Version=2.0.1.26, Culture=neutral, PublicKeyToken=null
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
```

Is there something I'm doing wrong?  Thanks!

**Comment by DirtyRacer1337** [comment]
`MediaBrowser.Common` part of jellyfin, check instalation

**Comment by PAHelper2** [comment]
Is it potentially a pathing issue?  I stuck the .dll in the top level "plugins" directory.  But I notice the InfuseSync plugin I have installed creates it's own directory (and then subdirectory) before putting the ddl file.

This is a docker installation, btw, if that helps.

**Comment by DirtyRacer1337** [comment]
Try to install from repository, thats correct way to plugin managment 
Repository url: `https://raw.githubusercontent.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/master/manifest.json`

**Comment by PAHelper2** [comment]
Sorry, I'm not understanding.  How do I use the repository url?  Is there someplace on the filesystem I'm supposed to put that manifest file?

**Comment by DirtyRacer1337** [comment]
Dashboard -> Plugins -> Repositories

**Comment by PAHelper2** [comment]
Aha!  So it turns out I was on version 10.5 which didn't have that.  I updated to 10.6, and was able to add the repository:

```
[19:50:06] [INF] [26] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: PhoenixAdult 2.0.1.26
```

Thanks!  Now I'll try to figure out how to use it.
