### ISSUE TITLE
Help with Enhanced search and Exact match (vixen/tushyraw etc.)

### ISSUE THREAD

**Issue by wyq977** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#106]
**Describe the bug**
First, thanks for this plugin! Amazing work.
I am quite new to this plugin but I am a bit confused about the naming/matching scheme it uses and it seems to be unable to fetch the metadata for the collections even tho the name of the folder follows the guide.

However, 1 or 2 files were able to match despite other can not match even using the identify function in jellyfin

These are the ones that are positive for match

`Cum4k - 2019-02-12 - Morning Wood Explosion - Lena Anderson/Cum4k - 2019-02-12 - Morning Wood Explosion - Lena Anderson.mp4`

`SisLovesMe - 2017-04-25 - Stepsisters Lucky Day - Lana Rhoades/SisLovesMe - 2017-04-25 - Stepsisters Lucky Day - Lana Rhoades.mp4`

Here are the folder where mp4 or mkv follows the smae name as the folder

```
Cum4k - 2019-02-12 - Morning Wood Explosion - Lena Anderson # WORK!
SisLovesMe - 2017-04-25 - Stepsisters Lucky Day - Lana Rhoades # WORK!


BLACKED - 2016-08-18 - Best Friends Share Two BBCs - Lana Rhoades And Leah Gotti
BLACKED - 2016-08-18 - Lana Rhoades And Leah Gotti
FamilySinners - Step Siblings Vol. 3 Scene 4 - Lena Anderson
Lana Rhoades - Stepsister Blackmails Peeping Stepbrother (2017)
Lena Anderson - BananaFever Part 1 (2020)
Lena Anderson - BananaFever Part 2 (2020)
NewSensatiosn - 2019-12-13 - Lena Anderson
TushyRaw - 2019-06-23 - Lena Anderson - My Very First!
Vixen - 2018-09-21 - after-dark-part-1
Vixen - 2018-09-26 - 100850
Vixen - 2018-10-11 - After Dark Part 3
Vixen - 2018-10-16 - After Dark Part 4
Vixen - 2018-10-26 - After Dark Part 5
```

I tried many times with vixen and tushyraw but it doesnt work in my case and I even tried the example in readme, also negative (with maunally identify afterwards):

`Blacked - Alecia Fox Joss Lescaf/Blacked - Alecia Fox Joss Lescaf.mp4`

Setting for this test library are as followed:
![Screen Shot 2021-11-03 at 5 44 29 PM](https://user-images.githubusercontent.com/27303600/140104859-9e599e65-dc62-4b2c-91ed-66259b91e860.png)
![Screen Shot 2021-11-03 at 5 44 36 PM](https://user-images.githubusercontent.com/27303600/140104874-6a028459-b4e6-4edf-9cdf-5c598087af4d.png)
![Screen Shot 2021-11-03 at 5 44 39 PM](https://user-images.githubusercontent.com/27303600/140104884-2fda991e-ea02-44aa-80e7-368239fa60f5.png)

**Include**
1. Jellyfin Version: 10.7.7
2. Plugin Version 2.6.2.46
3. Scene URL https://www.vixen.com/videos/after-dark-part-1
4. File Name  `Vixen - 2018-09-21 - after-dark-part-1/Vixen - 2018-09-21 - after-dark-part-1.mp4`
5. Log File

**Comment by wyq977** [comment]
To elaborate, this is an example I have for manual search, identif
![Screen Shot 2021-11-04 at 12 06 13 AM](https://user-images.githubusercontent.com/27303600/140230908-50340872-b857-4377-b9e9-911dcc9bf5ae.png)
y

**Comment by DirtyRacer1337** [comment]
Try [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)

You can't use url for matching and you should use name field

**Comment by wyq977** [comment]
The Nightly build seems to works fine with Vixen and TushyRaw problem. Ty!

I guess I will stick to this build until updates comes along. Thx
