### ISSUE TITLE
[question] Any way to get debug logging?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#11]
I'm using the 'Identify' function to try and get PhoenixAdult to find metadata.  However, when it fails, logging doesn't give me much reason why.

Here's an example:
I go to Identify, and then in the 'Name' filed I put
Pure Taboo - 2019-06-25 - The Daddy Interview

```
23:07:33] [WRN] [23] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 172.18.0.1. Time (slow): 0:00:09.6369123. http://jellyfin.myh0.me:443/Items/RemoteSearch/Movie
[23:07:33] [INF] [23] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 9643.5055ms 200 application/json; charset=utf-8
```

It should find this scene: https://www.puretaboo.com/en/video/puretaboo/the-daddy-interview/146872

I've also tried using actresses also, no luck.  If I use the sceneID, like: "Pure Taboo - 146872", it finds it immediately.

Debug logging might be able to help figure out what's going on.   I don't know if this is a PhoenixAdult bug from upstream, or a problem with the Jellyfin plugin.

**Comment by DirtyRacer1337** [comment]
Something was changed in Jellyfin and now it doesn't show errors. I fixed this error in latest version and forced to show errors
