### ISSUE TITLE
Mylf scenes including "mylf" in title don't work

### ISSUE THREAD

**Issue by npr0n** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#110]
Firstly, thank you so much for your continued work with this plugin. I have learned a lot about Emby, Jellyfin and the parsing of webpages over the last few months and must admit I have had several frustrating issues just resolve with an update of the plugin.

**Describe the bug**
Seems that scene titles including the name or an alias of the network or site get that part removed everywhere.
Example from line 36 in the log:
  searchInfo.Name: Mylf.21.07.12.Vivianne.Desilva.A.Mylf.Full.Of.Tricks
becomes (line 38);
  searchTitle: Vivianne Desilva A Full Of Tricks

Question:
Is there any way for me to enable the direct injection of the URL?
If I add the URL via the nfo, it doesn't get picked up as metadata, probably because I am only populating the <uniquieid type="PhoenixAdultURL"> and <phoenixadulturlid> fields with the URL.

I can open a discussion for this question if that makes it easier.

**Include**
1. Emby, Version 4.6.4.0 (Linuxserver Docker)

2. Plugin Version: 
Nightly Build (downloaded Sept 30, 2021) and Nightly Build (downloaded Nov 28, 2021), both reported as 10.7.0.0 within Emby.

3. Scene URL:
https://www.mylf.com/movies/a-mylf-full-of-tricks

4. File Name
Mylf_-_A-Mylf-Full-Of-Tricks_-_2021.mp4
NewMylfs.21.07.12.Vivianne.Desilva.A.Mylf.Full.Of.Tricks.XXX.1080p.MP4-WRB.mp4
Mylf.21.07.12.Vivianne.Desilva.A.Mylf.Full.Of.Tricks.mp4

5. Log File
[phoenixadult_mylf_log_cleaned.txt](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/7614360/phoenixadult_mylf_log_cleaned.txt)

Note: I have cut off everything before the search with all three file names (excluding .mp4) and replaced my servers hostname.

**Comment by DirtyRacer1337** [comment]
Mylf uses google search, you can get blocked for too much requests

You can use direct url for that site, like `mylf a-mylf-full-of-tricks`


> Question:
> Is there any way for me to enable the direct injection of the URL?
> If I add the URL via the nfo, it doesn't get picked up as metadata, probably because I am only populating the and fields with the URL.

Not possible for current realization, and you can't store URL in `ExternalId`, they will disappear if they have restricted symbols

**Comment by npr0n** [comment]
Thanks for the reply, but that's exactly the problem.
The initial parsing of the name seems to be the issue, since neither the google search nor the direct URL has "mylf" in the title itself. That's why I was asking for the URL injection.

I have a working bash script that is currently parsing kink.com and spits out the numerical IDs. Works like a charm as "channel.id" (like fuckingmachines.45180), unfortunately Mylf does not seem to use an ID system that could be parsed.
Also mylf changes their offers all the time which causes malformed html. But that's probably something for me to figure out later.

I'm pretty comfortable with creating nfo files by script now, the `ExternalId` I would guess is the content of the first two lines:
`  <uniqueid type="PhoenixAdult">16#16#twFe6Z8y6dFnJtZD</uniqueid>
  <phoenixadultid>16#16#twFe6Z8y6dFnJtZD</phoenixadultid>
  <uniqueid type="PhoenixAdultURL">https://www.kink.com/shoot/45180</uniqueid>
  <phoenixadulturlid>https://www.kink.com/shoot/45180</phoenixadulturlid>`
Is this ID in any way internal to PA and could I manually create it? I'm not that fit in C# to look over the code and understand how that comes to be.

`2021-11-29 14:36:18.572 Info PhoenixAdult: searchInfo.Name: mylf a-mylf-full-of-tricks
2021-11-29 14:36:18.581 Info PhoenixAdult: site: 23:0 (Mylf)
2021-11-29 14:36:18.581 Info PhoenixAdult: searchTitle: A Full Of Tricks
2021-11-29 14:36:18.581 Info PhoenixAdult: searchDate: 
2021-11-29 14:36:18.583 Info PhoenixAdult: provider: PhoenixAdult.Sites.NetworkMylf
2021-11-29 14:36:18.596 Debug PhoenixAdult: Requesting GET "https://www.google.com/search?q=site:mylf.com%20A%20Full%20Of%20Tricks"
2021-11-29 14:36:19.405 Debug PhoenixAdult: Requesting GET "https://mylf.com/movies/a-full-of-tricks"
2021-11-29 14:36:20.345 Info Server: http/2 Response 200 to 10.10.20.20. Time: 1918ms. https://emby.mydomain.test:8920/Items/RemoteSearch/Movie?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome&X-Emby-Device-Id=2b5b4f1d-fcd3-4ff4-9238-e3c36c522764&X-Emby-Client-Version=4.6.4.0`

**Comment by DirtyRacer1337** [comment]
> You can use direct url for that site, like `mylf a-mylf-full-of-tricks`

mylf.com/movies/**_a-mylf-full-of-tricks_**

**Comment by npr0n** [comment]
No. Doesn't work. Like I said in both posts. No matter what I put in the name, everything "mylf" gets removed. But it would be needed for that scene since it is in the name. "mylf.com/movies/a-mylf-full-of-tricks" becomes "PhoenixAdult: searchTitle: **Movies A Full Of Tricks**"

2021-11-29 23:48:29.008 Info PhoenixAdult: searchInfo.Name: **mylf.com/movies/a-mylf-full-of-tricks**
2021-11-29 23:48:29.010 Info PhoenixAdult: site: 23:0 (Mylf)
2021-11-29 23:48:29.010 Info PhoenixAdult: searchTitle: **Movies A Full Of Tricks**
2021-11-29 23:48:29.010 Info PhoenixAdult: searchDate: 
2021-11-29 23:48:29.010 Info PhoenixAdult: provider: PhoenixAdult.Sites.NetworkMylf
2021-11-29 23:48:29.010 Debug PhoenixAdult: Requesting GET "https://www.google.com/search?q=site:mylf.com%20Movies%20A%20Full%20Of%20Tricks"
2021-11-29 23:48:29.372 Debug PhoenixAdult: Requesting GET "https://mylf.com/movies/movies-a-full-of-tricks"

**Comment by npr0n** [comment]
Not sure how else I am supposed to describe the issue

**Comment by DirtyRacer1337** [comment]
`mylf a-mylf-full-of-tricks` not `mylf.com/movies/a-mylf-full-of-tricks`

**Comment by DirtyRacer1337** [comment]
This should also help, 3107b46368b9030ac41b767dd6cf66a42e47fe87

**Comment by npr0n** [comment]
I'll check the change out tomorrow, bc. with both as "name" the log indicated that the search title was missing the "mylf".

**Comment by npr0n** [comment]
The change fixed it! Thank you so much for your help!!!
