### ISSUE TITLE
Editing Multiple Videos Metadata?

### ISSUE THREAD

**Issue by tequiza** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#112]
hi, in Jellyfin, is it possible to edit multiple videos' metadata in one go?
this would be useful when plugin sometimes fails to identify the scene.

Example: i have a folder called Kate which has 100 Kate Someone scenes inside. I want to be able to add People/Actor: Kate Someone to metadata of all 100 videos inside that folder.

I'm using the latest nightly version. thank you.

**Comment by DirtyRacer1337** [comment]
That question to Jellyfin devs, Plugin only provide info
