### ISSUE TITLE
Failure to Match when using Identify Option.

### ISSUE THREAD

**Issue by Middlepepper** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#113]
Just want to better understand how we use the plugin.

When I try to use the "Identify" option to match metadata I get no results. 

I've tried this in Name, PhoenixAdult Movie Id and PhoenixAdult ID Movie Id

What need to be put into here when trying to manually sync metadata? As there two fields on not sure which is the right one.

I've been using manyvids - 3230197 as an example though the filename itself is different.

![image](https://user-images.githubusercontent.com/18419688/146473882-5add37b8-58f6-4e89-ac37-ce4634aa45bd.png)

**Include**
1. Jellyfin
2. 2.6.2.46
3. https://www.manyvids.com/Video/3230197/Dawn-Rewards-Her-Arcanine/

**Comment by DirtyRacer1337** [comment]
Still actual, #83

Use this version [nightly build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)
