### ISSUE TITLE
Genres handling

### ISSUE THREAD

**Issue by wyq977** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#115]
Now, I am using infuse on my ios and mac for access to jellyfin server.

The problems is that the genres or the tags of the adult content outnumber the movie/tv show genres such as "Comedy" way too much. So is there a way to disable genres from adult lib in jellyfin (server end), disable genres in infuse (client end)

I know this is out of a scope of what a plugin can do I am just wondering if someone can help explain.

Any help would be appreciated, Thx!

**Comment by DirtyRacer1337** [comment]
Try [nighty build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly), with this update 327567fcecd8bca97b0289d99f7c0562c77e473b

Check `Disable Genres Saving` In plugin settings and run `Cleanup Genres` task

**Comment by wyq977** [comment]
Thx for the quick help!! Is this feature going to main build?

Really appreciate ur help

**Comment by DirtyRacer1337** [comment]
No, you should install it manually

Btw actors have same problem, #19

**Comment by wyq977** [comment]
> Btw actors have same problem, #19
Ty for reminder, will check that out.

I mean i have solved the issue by installing nightly build, just asking if this option will be incorporated in future releases as I saw you commit on the master br.

**Comment by DirtyRacer1337** [comment]
> > Btw actors have same problem, #19
> > Ty for reminder, will check that out.
> 
> I mean i have solved the issue by installing nightly build, just asking if this option will be incorporated in future releases as I saw you commit on the master br.

Yes it will be

**Comment by wyq977** [comment]
Ok, close it since its been resolved
