### ISSUE TITLE
Identify Doesn't return any results

### ISSUE THREAD

**Issue by bejita78** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#12]
I've installed the plugin for Jellyfin both the traditional way by making the dll or via your repository. Either way, I am unable to search for anything. I select identify and put in information, even information I know from other issues are supposed to show positive results. I get a blank screen. My log also doesn't show anything has happened.

What is going on?

**Comment by DirtyRacer1337** [comment]
Try new version
