### ISSUE TITLE
Nothing gets searched on emby

### ISSUE THREAD

**Issue by DoucheHellSung** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#123]
**Describe the bug**
So i searched for [Brazzers] Day With a Pornstar - Field Trip Fuck but it didn't yield any result, but if same searched on plex. It works perfectly. Same happens with almost all files

**Include**
1. Emby
2. 2.6.2.46
3. -
4. [Brazzers] Day With a Porn star - Field Trip Fuck
5. Can provide if this is actively monitored

**Comment by DirtyRacer1337** [comment]
Looks like some problems on site, got timeout error, but it's works now.
You can try on [nightly build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly), if it's still doesn't work

**Comment by DoucheHellSung** [comment]
Nightly doesn't even come up in my plugin on emby. Is it expected behavior?  

BTW you are literally GOD for the bundle which you have created for plex Its dope, hope emby reaches the same height. As an IT guy myself, one question I wanted to ask out of curiosity. Is .NET limiting you in some way for developing this? As compared to plex bundle which I guess is on python!

**Comment by DirtyRacer1337** [comment]
Check [sitelist.md](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/blob/master/docs/sitelist.md), mrluckypov not supported, you can try to use [MetadataAPI](https://metadataapi.net/) to get it, there is separate plugin for it, [Jellyfin.Plugin.ThePornDB](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB)

I'm ok with C#, it's not limiting me, but python much easier

**Comment by DoucheHellSung** [comment]
> Check [sitelist.md](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/blob/master/docs/sitelist.md), mrluckypov not supported, you can try to use [MetadataAPI](https://metadataapi.net/) to get it, there is separate plugin for it, [Jellyfin.Plugin.ThePornDB](https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB)
> 
> I'm ok with C#, it's not limiting me, but python much easier

Oh that makes sense, 

I asked so because searches yield more results on plex than emby also size of plex bundle is more.(because of binaries i guess).

Also is there any discord or tg group for testers?

**Comment by DirtyRacer1337** [comment]
Nah, I don't anything like discord.

Adultempire works, I tested it right now

**Comment by DoucheHellSung** [comment]
![image](https://user-images.githubusercontent.com/96594716/153741265-9e97f278-18db-4e8e-9a58-5b690448dd3c.png)

This gives back no results but this scene can be found [here ](https://www.adultempire.com/3102489/the-bet-porn-videos.html).

Also is there any way to use phoenix adult id when identifying anything?

**Comment by DirtyRacer1337** [comment]
Id was not supported, try with this 0b05a3c04dccd1556d4a0afb5774a52a52cfcbc9

phoenix adult id for storage only

**Comment by DoucheHellSung** [comment]
Also boss, theporndb's latest development release doesnt work on emby , some newtonsoft json error, if you have some spare time i can provide logs for that also.

**Comment by DirtyRacer1337** [comment]
> The latest nightly once loaded in emby doesn't show up in metadata fetcher and also doesnt show up in my plugin.

Fixed 3fcd74f67f8102a4eee0f4f864235524c1710626

> Also boss, theporndb's latest development release doesnt work on emby , some newtonsoft json error, if you have some spare time i can provide logs for that also.

Actually, it's shouldn't work, here compiled one, [Emby.Plugins.ThePornDB.zip](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/8055309/Emby.Plugins.ThePornDB.zip)

**Comment by DoucheHellSung** [comment]
> > The latest nightly once loaded in emby doesn't show up in metadata fetcher and also doesnt show up in my plugin.
> 
> Fixed [3fcd74f](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/commit/3fcd74f67f8102a4eee0f4f864235524c1710626)
> 
> > Also boss, theporndb's latest development release doesnt work on emby , some newtonsoft json error, if you have some spare time i can provide logs for that also.
> 
> Actually, it's shouldn't work, here compiled one, [Emby.Plugins.ThePornDB.zip](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/8055309/Emby.Plugins.ThePornDB.zip)

You , sir are definition of awesomeness, everything is working fine now. I will keep testing emby deeply and let you know. Thanks again for your contribution to community. 👯‍♂️
