### ISSUE TITLE
Clips4sale exact match returns incorrect result

### ISSUE THREAD

**Issue by DoucheHellSung** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#126]
**Describe the bug**

**Include**
1. Emby
2. Plugin Version - Latest Beta
3. Scene URL - https://www.clips4sale.com/studio/60555/14680201/the-peeping-paperboy-720p
4. File Name - Lady fyre the peeping tom

I did manual search by this query and it returned multiple results specific to studio , but this particular scene not theie.
Clips4sale - 60555 - 14680201 - https://www.clips4sale.com/studio/60555/14680201/the-peeping-paperboy-720p

Screenshot from log with date 
![image](https://user-images.githubusercontent.com/96594716/154790777-638037e6-e7f7-4485-b2bb-e609a1e8f6f2.png)

**Comment by DirtyRacer1337** [comment]
Site doesn't work for me, #101 

`Clips4sale - 60555 - The Peeping Paperboy`, should work

**Comment by DoucheHellSung** [comment]
> 

Perfect

**Comment by DoucheHellSung** [comment]
HI @DirtyRacer1337 I tried the same query on emby beta server 4.7.0.28 , it didn't return any result

![image](https://user-images.githubusercontent.com/96594716/156502560-6294f89e-aa69-4633-b25f-c1a8a810ba30.png)

**Comment by DirtyRacer1337** [comment]
#101

**Comment by DoucheHellSung** [comment]
but its working fine on stable !
