### ISSUE TITLE
phoenixAdult produce so many file in logs folder is normal?

### ISSUE THREAD

**Issue by plsharevme** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#127]
**Describe the bug**

I found out phoenixadult logs folder produce so many xxxx.json.gz file **over 450,000 files.**

location `\Jellyfin\Server\plugins\Jellyfin.Plugin.PhoenixAdult\logs`

it have so many log files.............is this normal? should i uninstall 1st ?

cause my hdd is ssd massive write will short the lifepan.

thanks
![无标题](https://user-images.githubusercontent.com/64370408/155129886-c12a1577-fb67-4a28-b0c6-9da5030b9d60.jpg)

**Comment by DirtyRacer1337** [comment]
also `Cleanup Service Data`, should cleanup all old files (3 days) and it's should be runned every day

**Comment by plsharevme** [comment]
okay , Tq for your reply !!!

appreciate.
