### ISSUE TITLE
Clips4sale scrapper doesnt fetch actor data

### ISSUE THREAD

**Issue by DoucheHellSung** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#128]
Describe the bug
The search results are perfect but it doesnt capture actor data , on the other hand, in plex it captures it. Is it something not possible on emby?

Include

EmbyPlugin Version - Latest Beta
Scene URL- https://www.clips4sale.com/studio/60555/14680201/the-peeping-paperboy-720p
File Name - Lady fyre the peeping tom

**Comment by DirtyRacer1337** [comment]
Plex use manual data for it, https://github.com/DirtyRacer1337/PhoenixAdult.bundle/blob/32ebce46891b28263c79c1d33454c400851afed0/Contents/Code/siteClips4Sale.py#L1644

It's possible, just it's takes too much time and I don't like that solution

**Comment by DoucheHellSung** [comment]
> Plex use manual data for it, https://github.com/DirtyRacer1337/PhoenixAdult.bundle/blob/32ebce46891b28263c79c1d33454c400851afed0/Contents/Code/siteClips4Sale.py#L1644
> 
> It's possible, just it's takes too much time and I don't like that solution

Oh, so do you have some better solution in mind for the future. Also, I saw you added tinysis to the plex plugin, will it be added here? Do you use plex because I see there are lots of sites support for plex but not emby/jellyfin

**Comment by DirtyRacer1337** [comment]
Added 1175fbeb39ad54d5b77dea22e0ae396daaabfbcb

I'm not using anything anymore and not add support for new sites, PornDB (MetadataAPI) doing same thing, but centralized, so I'm helping them, that's more productive

**Comment by DoucheHellSung** [comment]
> Added 1175fbeb39ad54d5b77dea22e0ae396daaabfbcb
> 
> I'm not using anything anymore and not add support for new sites, PornDB (MetadataAPI) doing same thing, but centralized, so I'm helping them, that's more productive

Ye, makes sense. Thank you so much 😁
