### ISSUE TITLE
Not a bug, but an enhancement request

### ISSUE THREAD

**Issue by DoucheHellSung** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#129]
Describe the enhancement
Can we get phoenixscrapper as a search source engine for thumbs also when editing images for scene?

**Comment by DirtyRacer1337** [comment]
Wdym, plugin can search images, if video have been matched

**Comment by DoucheHellSung** [comment]
Like if i want to set custom thumb

**Comment by DirtyRacer1337** [comment]
It's would be same image as for backdrop, no point to add it
