### ISSUE TITLE
[Help] Instructions to set it Up

### ISSUE THREAD

**Issue by roshanconnor123** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#13]
Hello
I couldn't see any setup Instructions for this Plugin
Can someone provide me a Working method to add it to my Jellyfin
I must say that I never installed any other unofficial in My Jellyfin
Thank you

**Comment by DirtyRacer1337** [comment]
https://jellyfin.org/docs/general/server/plugins/index.html

https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/latest
or Plugin Repository: https://raw.githubusercontent.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/master/manifest.json

**Comment by roshanconnor123** [comment]
Thank you very much
