### ISSUE TITLE
GenderX tries genderx.com instead of genderxfilms.com

### ISSUE THREAD

**Issue by npr0n** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#131]
**Describe the bug**
Seems to me that matching for genderx tries to get info from https://genderx.com/ instead of the correct https://genderxfilms.com

**Include**
1. Jellyfin or Emby - Emby
2. Plugin Version - Nightly 2022.02.22
3. Scene URL - https://www.genderxfilms.com/en/dvd/Trans-Babysitters-4/85309
4. File Name - GenderX.21.11.04.Ivory.Mayhem.Trans.Babysitters.4.XXX.2160p.MP4-Narcos.mp4
5. Log File
[genderx-errorlog.txt](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/8171211/genderx-errorlog.txt)

P.S. Thank you once again for the great work!

**Comment by DirtyRacer1337** [comment]
Fixed 27e8144c64cb92482854cc7bc2792b1f2d3c519e

Just run `Update Database` task
