### ISSUE TITLE
Use Backdrop as Primary Image

### ISSUE THREAD

**Issue by sjiawjbssj** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#137]
It would be nice if there was an option to use the backdrop as primary image because on AndroidTV it only shows the primary image or thumbnail. Most Videos don't have a primary Image or the image is just a cropped version of the backdrop.

Client: Jellyfin AndroidTV (latest version)

**Comment by DirtyRacer1337** [comment]
1. I even installed `Jellyfin AndroidTV` and it's can show backdrop
2. Plugin always set primary image, and backdrop if possible, so it can't have backdrop without primary

**Comment by sjiawjbssj** [comment]
Sorry I probably worded that badly.
The Backdrop is shown as backdrop but I'd like to use the picture that's fetched as backdrop also as primary picture because the primary picture that's selected now is either a badly cropped version of the backdrop picture or a screenshot from the video.
On PC I can select that "Thumb" and it shows the backdrop image like it's the primary image.
I hope I explained it better this time.
Thank you for answering.

**Comment by DirtyRacer1337** [comment]
Which videos, give me link, `PhoenixAdult Id` or something to identify, I will look

**Comment by sjiawjbssj** [comment]
It's pretty much every video.
Example: https://metadataapi.net/scenes/1305904

![Screenshot_20220319-232053__01](https://user-images.githubusercontent.com/101941309/159140464-d457cfb0-ea10-4633-8973-6849e9c1a840.jpg)

As you can see in the attached Screenshot the Primary Image is just a badly cropped version of the backdrop.
It would also work if the backdrop images would be set as banner because that can be shown on AndroidTV as well.
Sometimes the banner gets set correctly but mostly like with the example above it's just a cropped version of the backdrop as well.

**Comment by sjiawjbssj** [comment]
Here is an example where backdrop and primary image are the same so it get's displayed property.
Link: https://www.freeusefantasy.com/movies/endless-desire-possibilities

![Screenshot_20220319-233152__01](https://user-images.githubusercontent.com/101941309/159140726-66009703-e7e5-4ff1-8fd2-259eef6d035e.jpg)

So if the image that gets returned by the website/porndb as backdrop would also show up as a primary image in the image selection that would fix my issue.

**Comment by DirtyRacer1337** [comment]
If it only happens with PornDB I added background to primary, 1f5029e54e86d8b58215296aad2d38a50a3bbed4

**Comment by sjiawjbssj** [comment]
Thank you very much. I'll try it out when the update is available via the repository.

**Comment by DirtyRacer1337** [comment]
better install [Nightly Build ](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly) manually, last update was 9 mount ago

**Comment by sjiawjbssj** [comment]
Oh yeah, thanks. I didn't notice that
