### ISSUE TITLE
Latest Stable AND development release do not load on Jellyfin 10.8.0

### ISSUE THREAD

**Issue by cliffalbert** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#143]
**Describe the bug**
PhoenixAdult plugin does not load and reports 'Unsupported' in plugin page on Jellyfin 10.8.0.
The latest stable release and the development release both fail to work.

**Include**
1. Jellyfin 10.8.0 on Linux (Ubuntu 22.04 LTS)
2. Plugin Version - Stable 2.6.2.46 and latest development
3. Scene URL - not relevant
4. File Name - not relevant
5. Log File

[2022-05-11 15:05:32.369 +02:00] [ERR] Failed to load assembly "/var/lib/jellyfin/plugins/PhoenixAdult/Jellyfin.Plugin.PhoenixAdult.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.AddCollection' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupActors' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupGenres' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupServiceData' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.UpdateDatabase' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.AddCollection' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupActors' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupGenres' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.CleanupServiceData' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'PhoenixAdult.ScheduledTasks.UpdateDatabase' from assembly 'PhoenixAdult, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by DirtyRacer1337** [comment]
https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly
