### ISSUE TITLE
[error]BlackedRaw Files not fetching Metadata

### ISSUE THREAD

**Issue by roshanconnor123** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#15]
Hello
I renamed my Blackedraw Files this way (according to the Format)
```
BlackedRaw - 2017-10-19 - lana rhoades 4k.mp4
BlackedRaw - 2017-11-03 - kleio valentien 4k.mp4
BlackedRaw - 2017-11-08 - alina lopez 4k
```
But its unable to fetch any metadata at all
Please look into it
Thank you

Ps: I i tried with BellesaFilms - Worked well for 70 Files

**Comment by DirtyRacer1337** [comment]
1. I know about that problem, you probably get message in log `Year detected (probably important data was stripped), required manual identify`. I already place a fix for it on jellyfin repo
2. BlackedRaw not supported, check sitelist

**Comment by roshanconnor123** [comment]
> 1. I know about that problem, you probably get message in log `Year detected (probably important data was stripped), required manual identify`. I already place a fix for it on jellyfin repo
> 2. BlackedRaw not supported, check sitelist

Thank you for your Reply
Will wait for that Update

**Comment by DirtyRacer1337** [comment]
Also I forgot to tell that you can disable year warning in plugin setting, but then you probably get only `BlackedRaw` from FileName, you can add year at the end of file to fix that.

BlackedRaw probably never be supported, because I can't find cloudflare bypass library

**Comment by DirtyRacer1337** [comment]
@roshanconnor123 BlackedRaw (and others) added in ffd396d4a281bea966e3392624dc83aaf9a4f043
