### ISSUE TITLE
[Question/Feature Request] Are The Releases Stable? & Create A Plugin Repository

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#16]
## question
Are the releases stable? Or would this be considered alpha/beta still?

## feature request
would suggest creating a jellyfin repository for users to add to stay up to date
https://jellyfin.org/docs/general/server/plugins/index.html#3rd-party-plugin-repositories

**Comment by DirtyRacer1337** [comment]
You can consider it like stable release

It's have repository  `https://raw.githubusercontent.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/master/manifest.json`
