### ISSUE TITLE
Scanning library crashes Jellyfin

### ISSUE THREAD

**Issue by Hellcrusher3092** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#163]
**Describe the bug**
When running a library scan with PhoenixAdult plugin set as the only metadata scraper, Jellyfin crashes after a few minutes of the scan.

**Include**
1. Jellyfin docker - nyanmisaka/jellyfin:latest
2. Plugin Version - 2.7.0.47
3. Scene URL
4. File Name 
5. Log File

![Jellyfin log](https://user-images.githubusercontent.com/111262220/184576175-eb3a191d-a138-4354-92b0-81fb07322c6a.PNG)

**Comment by DirtyRacer1337** [comment]
Same as #161, try [nightly build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)
