### ISSUE TITLE
Feature Request / Suggestion: Installation Instructions

### ISSUE THREAD

**Issue by MajesticMaerlyn** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#17]
Hi,

Glad to see this being ported to Emby / Jellyfin - as TBH I only run Plex so I can run this. 

And I see we can do donations here as well - yippee!

My suggestion (and query) - include some kind of installation guide as I believe Emby installation is completely different from just dropping in a plugin directory like Plex.

Cheers

**Comment by MajesticMaerlyn** [comment]
Dang it, I found how to install by searching [Closed Issues]. 

Maybe just add a link to repository or Emby DLL in readme. But feel free to close. 

Sending some donations over :)

**Comment by DirtyRacer1337** [comment]
I added small guide in 68d75458e0f0a5e817835b83dff610bc1b3e1921

It's have link to the latest release page, right under description.
