### ISSUE TITLE
Evil Angel Stopped Working 

### ISSUE THREAD

**Issue by johnbar459** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#175]
Hi,

Metadata for Evil Angel titles seems to have stopped working. It was fine a few months ago with same version, so not sure what changed on their end. I've tried several different scene/title naming formats that worked fine in the past including the sample for EvilAngel in the real world examples. Trying to identify the title brings up no information.

Jellyfin 2.7.0.47

**Comment by DirtyRacer1337** [comment]
try dev build, if that will not helps, then meh, this site is banned in my country, also it have cloudflare protection, use flaresolverr
