### ISSUE TITLE
fail to get data from teamskeet.com

### ISSUE THREAD

**Issue by muztag** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#18]
fail to get data from teamskeet.com.
I try to debug, and I found: "var http" in line 25 "NetworkMylf.cs" ,get a Cloudflare captcha page.

**Comment by DirtyRacer1337** [comment]
Works for me, what filename you use? If it's really Cloudflare then I can't do anything with it.

**Comment by muztag** [comment]
Any filename ,or manual search, is same.
I can visit teamskeet in browser without Cloudflare captcha page, but the plugin fail.

Maybe, browser info and cookie is the key point. I'll try to solve it. 

Can you please tell me, how to make plugin dlls and depending dlls in one file? when I debug, I put all depending dlls in emby\system floder and edit emby.depd.json. I don't know if this is the best method.

I'm sorry for my poor English, and I wish I have made myself clear.

**Comment by DirtyRacer1337** [comment]
To make dll in one file open `ILRepack.targets` and add to `Condition` `'$(Configuration)'=='Debug.Emby'` or use it directly https://github.com/gluck/il-repack

**Comment by DirtyRacer1337** [comment]
Added CloudFlare bypass by [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) in [2.4.2.42](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/2.4.2.42)
