### ISSUE TITLE
Unhandled exception VS Status: Malfunctioned

### ISSUE THREAD

**Issue by robsonsobral** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#181]
Hi! I wish you a happy 2023.

The current version crashes on any image downloading failure, and the current nightly build doesn't start.

Thank you!

**Include**
1. Jellyfin
2. 2.7.0.47
3. -
4. -
5. -

**Comment by DirtyRacer1337** [comment]
Fixed 31568192adeba6700e7f436ba6120c017e7f3b8c
