### ISSUE TITLE
Does this plugin support full movies or only scenes?

### ISSUE THREAD

**Issue by TheEvilMonkey** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#187]
More of a question than a bug...have some full movies that are in AdultDVEmpire.  Currently TPDB scraper doesn't pick them up so wondering if this one does?

**Comment by DirtyRacer1337** [comment]
If you can find it [here](https://www.adultdvdempire.com/allsearch/search?fq=media_id:2&q=), then yes
