### ISSUE TITLE
[Feature Request] Implement A Toggle To Disable Actor/Actress/Star Metadata Pulls

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#19]
There is currently a "bug" in Jellyfin, where it allows users who do not have access to specific libraries to search for actors/actresses that are attached to videos in libraries that they do not have access to. I assume this was intended design and not a bug, I have brought it up with them but it's been an issue for quite some time and it seems like they need to work-on a partial rewrite of their backend before they can do something like this, not sure. I have suggested the ability to just allow disable searching for specific users all together but it was ignored by them so far, not sure what the current status is on all this tbh.

So for example, if you have adult videos in library2, and you have a user that does not have access to library2, if you go on their account and search for an actress name that is only attached to a video on library2, it shows up in the search. This is of course possibly undesireable on a shared server (there is an argument that a shared server for this content may not be the best idea too, but still..)

It would be nice to have a setting for your addon (toggleable from the jellyfin addon plugin page) that simply disables the plugin from grabbing any actor/actress metadata, and also if a library is forced a full refresh of metadata, it removes any actors/actresses that it originally grabbed in the past. This would be great as a workaround until this can be resolved on jellyfin.

**Comment by DirtyRacer1337** [comment]
Added in 280fa40e7291eaf23be2ad93751779a0ce08ea12

**Comment by grravity** [comment]
Awesome, appreciate that heavily!

**Comment by grravity** [comment]
This seems to be broken in the latest release?
I can search for Actresses in Jellyfin search and they appear. I click on them, and they show the titles associated (or just show no videos for users without library permissions). However the actresses still seem to show in search.

**Comment by DirtyRacer1337** [comment]
"Refresh People" task should delete empty entries.

**Comment by grravity** [comment]
I just ran cleanup actors, then refresh people and it did not seem to fix.

Plugin: 2.3.4.38

Jellyfin: 10.6.4

OS: Windows 10

**Comment by DirtyRacer1337** [comment]
Yes, confirmed, they still appear in metadata.

**Comment by grravity** [comment]
Thank you

**Comment by grravity** [comment]
Can you confirm if it is working? I just tried literally deleting my People metadata folder, and rescraping and it pulled a few but not all. I see "Rae Lil Black", "Johnny Sins", "Hazel Moore", in searches.
I don't even have scraping on for that library, so idk if plugins just pull from the People databases even if it doesn't find matches? Like it just scrapes the whole database?

I don't see some of the people I used to though, like "Hatano Yui", "Julia", etc.

**Comment by DirtyRacer1337** [comment]
Yes, I checked. 

"Refresh People" task should delete empty entries, also "Scan Media Library" should verify database.

You can check metadata, there is bug in jellyfin with people, if type's field is empy, than people exist in metadata, but not displayed, that not happen on emby.

Are you on [2.3.6.40](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/2.3.6.40)? Which one still have people, If you manualy refresh metadata they still appear?


> I don't see some of the people I used to though, like "Hatano Yui", "Julia", etc.

What are you mean?

**Comment by grravity** [comment]
>Are you on 2.3.6.40

Yes

>What are you mean?

I mean, it grabbed some metadata, but not all. If I didn't disable people, it usually grabbed people like Julia, and Hatano Yui.
Now they're not appearing, it seems like it's grabbing some people but not all.

>Refresh People" task should delete empty entries, also "Scan Media Library" should verify database.

Yeah did both of these, also I literally tried just completely deleting my `jellyfin/metadata/People` folder so to my knowledge, those people (Johnny Sins, Hazel Moore, Rae Lil Black, etc) should not even exist in the database. However when I search in Jellyfin they came back up. I also see them in the newly created People folder locally. They shouldn't even be there, I deleted the whole People folder to force it to rebuild.

**Comment by DirtyRacer1337** [comment]
> I mean, it grabbed some metadata, but not all. If I didn't disable people, it usually grabbed people like Julia, and Hatano Yui.
Now they're not appearing, it seems like it's grabbing some people but not all.

Seems familiar, same thing happend when I migrate from 10.5 to 10.6. Problem was in `library.db`. Try to save that file and go on fresh db file. This helps me that time. I'm sure there is a way to fix that database file.

**Comment by grravity** [comment]
That'd reset all my ID's to the items breaking favorites correct?
Was trying to avoid that, otherwise I would've just fresh installed.
Hmm

**Comment by DirtyRacer1337** [comment]
You can rename data folder, after test rename it back. Maybe I'm wrong.

Try add manually that people who not appear, `Hatano Yui`. If it's disappear then I was right.

But if you migrated from 10.5 like me, probably this is only solution. I think my plugin can't break anything, it's just provide metadata.
