### ISSUE TITLE
JAV Name Order Preference & Place JAV ID in Title

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#20]
Requesting the ability to pick naming preference for JAV idols (Last Name, First Name or First Name, Last Name), without affecting Western Names.

Also requesting the ability to choose to place the ID of JAV titles in the title, either at the beginning or end.

**Comment by DirtyRacer1337** [comment]
> Requesting the ability to pick naming preference for JAV idols (Last Name, First Name or First Name, Last Name), without affecting Western Names.

Right now for JAV, plugin have two modules `JavLibrary` and `R18`. I choose R18 naming style, only that style gives image for actors.

> Also requesting the ability to choose to place the ID of JAV titles in the title, either at the beginning or end.

Already did it. In search result in beginning of title and in metadata original title property.

**Comment by grravity** [comment]
As for the first, JavLibrary uses the formal Japanese naming which is why I requested the feature. Last Name, First Name is the general naming scheme for Japan

**Comment by DirtyRacer1337** [comment]
Added in 4919b959fc708d47d4e3c58a2214936d34192779
