### ISSUE TITLE
Update sitelist?

### ISSUE THREAD

**Issue by UncertainMongoose** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#218]
Some sites listed as separate parent sites in the sitelist.md have been acquired by other parent sites within the past 2 years (which is when the sitelist.md was updated last). For example, Girlsway is now an AdultTime "channel" and the site architecture may have changed since the time the sitelist.md file was written. 

Is this something that needs to be updated or do the same file naming conventions apply regardless of the fact that some sites have become channels of other sites?

**Comment by DirtyRacer1337** [comment]
That list just for info, should work anyway
