### ISSUE TITLE
Unable to obtain data from Adult Time

### ISSUE THREAD

**Issue by stoals** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#24]
**Metadata Not being pulled from Adult Time - Emby**
Any build dated after the Oct 24 build is unable to pull data from Adult time.

This could be user error, but is not happening on Oct 24 build.

**Comment by stoals** [comment]
Retried after a clean install of Emby and the plugin. Issue continues.

**Comment by DirtyRacer1337** [comment]
Fixed in 528bf5e0900eea12031e88a8db1db9994f41d7b7

**Comment by stoals** [comment]
Will do! Thanks that was crazy fast response time.

**Comment by stoals** [comment]
Looks like that did it. Thank you again.
