### ISSUE TITLE
[Bug] Unable To Fetch JAV Metadata & Unknown Metadata Seems To Fixate On One Fetch

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#25]
As requested, here is the issue for being unable to fetch JAV metadata.
To be clear, I was having some issues with Jellyfin after renaming my libraries, but they all seem cleared up now except for two issues.
I've been using PhoenixAdult for a bit now, and I haven't seem to had issues, but I can't remember if I used any of the previous versions for my JAV library.

I was using https://github.com/imaginary-upside/JellyfinJav that for JAV, and it worked flawlessly however I was hoping to switch to this for a more all in one.

I want to say, I ran a metadata fetch for only Phoenix (disabled JellyfinJAV) before I messed with my library (which was giving me issues with my Jellyfin), and it found metadata no problems. I could be wrong on that however, I really do not remember. 

# Unable to fetch JAV metadata

**Directory Structure Examples:** 
```
Videos/NSFW/JAVIDOL/JAVCODE/JAVCODE.mp4
Videos/NSFW/Fukada Eimi/[DOKS-506]/[DOKS-506].mp4
Videos/NSFW/Fukada Eimi/[DOKS-506] (1080p)/[DOKS-506] (1080p).mp4
```

Log: https://bin.snopyta.org/?43bb26b5c84e31bf#EPCGNCtMVhRGjTi5hzVJRBsQP1JSgvGmeu54eNGi4Djt
It repeats itself with almost all the titles it tries fetching, I just grabbed a small portion of the log instead of dumping the entire thing.

# Unknown Metadata Seems To Fixate On One Fetch

This one is a weird error, so upon renaming my libraries and having issues with Jellyfin, it simply took a full 24hours to refresh all the libraries and it rescanned everything. 
Now first I want to state, my NSFW libraries, aren't permitted to all users. And I have the NSFW plugins disabled for those libraries for metadata fetching, so here's what I don't understand.
Across ALL my libraries, I kept getting a metadata fetched for movies that it seemed to not recognize (weirdly named files, stuff I had named custom that tried fetching and got overridden with this metadata, etc.) and this wasn't only on my NSFW libraries, it happened on files across all my libraries. Just a few, not all the files.

But it was always the SAME metadata it was grabbing for the (what I assume to be unknown metadata, almost like it was a placeholder if it couldn't recognize the file). And it was called `"What Are You Doing? You're Going To Slip It Inside Me!" My Way-Too-Nice Stepmom Agreed To Let Me Fuck Her Thighs But We Went Further. Aina Shinkawa 7"`. Currently there are 2 files in my JAV library that scanned as this. 
I fixed the ones manually in my other non NSFW libraries. However Idk where it's pulling this title from, I have no files named this in my library, nor have I ever had any files with this title.

And the other confusing part, is why it was labeling movies in my other libraries that have never had the plugin enabled for those libraries.
Unless when I renamed them, it enabled it by default, but when I went under manage library, it didn't look like it was enabled if I remember correctly. So idk. 
I'll check the log after it finishes the rescan, and if I see anything when searching for that title in the logs, I'll edit it in. But so far I see nothing, it's still rescanning though.

# server

Server OS: Windows 10 Home
Reverse Proxy: NGINX
Jellyfin Version: 10.6.4
PhoenixAdult Version: 2.3.1.35

**Comment by DirtyRacer1337** [comment]
It was easier than I thought. 
The name should start with `JAV`, its a shortcut for `JAVLibrary`. I can't make support multiple sites without it.

**Comment by grravity** [comment]
Welp Rip. I can't change all my titles to match that. Could it not just be added as a seperate metadata option specifically for JAV? Guess I'll just use the JellyfinJAV plugin for JAV for now :/

Any idea on the 2nd issue?

**Comment by DirtyRacer1337** [comment]
Do you have logs, when it happed, I have suggestion, but if file not start with site name, plugin does not get any metadata.

**Comment by grravity** [comment]
I checked the logs, and I don't know. I searched that title and it wasn't in there. Idk where it's pulling that from, maybe it was just a bug though.

As for the JAV metadata, checking for the name of the root folder being called JAV (Videos/NSFW/JAV/JAVID/JAVID.mp4) could work, if that's what you mean. However it may not work for everyone, especially if they are seeding files, as changing the name of that root directory will break all their files. They'd have to create symlinks at minimum however on Windows that can be a pain.

However, a more solid idea seems to be to just add an option under library management where you select what plugins you want for the metadata, and just add a seperate option for JAV. If a user chooses the PhoenixJAV option and not the PhoneixPorn option, for a specific library, it only grabs from JAV databases.

Unless I'm failing to understand the issue, this seems like it'd be the best option no? 

If you look at the JellyfinJAV plugin I linked, that developer has seperate options for R18, JAVLibrary, etc. That you can choose individually for each library (similar to how you can set TheMovieDB, AniDB, etc). I'm not suggesting creating individual options for each JAV provider, but simply a JAV option that handles them all.

So would it not make sense to just seperate JAV from Porn by just making them two different options? If a user wants to fetch JAV for the libraries, they select the JAV plugin, for porn they select porn, or if it's a mixed library they just select both?

This way they don't need to worry about directory names, symlinking, or anything. It seems like it'd be the most universal, solid, option? Again unless I misunderstood the issue at play. It sounds like it just needs to see JAV to say it wants to fetch from JAV, so I'm thinking the above should work, just by forcing it to search for JAV, instead of it looking for the JAV keyword?

**Comment by DirtyRacer1337** [comment]
That's also should help, 72138bd8f2ea1b5bdd183f248a35bb2338ae6080
That's add `JAV` to search query, if it looks like `ABC 123` and if name have only two words

**Comment by grravity** [comment]
Ok, just tried the latest version and it seems to be grabbing the JAV titles now.
