### ISSUE TITLE
Not pulling any info from brazzers sites

### ISSUE THREAD

**Issue by dsmith593** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#26]

**Comment by emptyellipsis** [comment]
I'm also running into this issue with the latest one, just seemed to stop working

**Comment by DirtyRacer1337** [comment]
@emptyellipsis Sorry for that, I fixed it already in 4c9dfcf1738d0ca403f5d3fb71c07c302658bb24. It's not in release yet.
You can fix it right now by cleaning `TokenStorage` field in configuration file and restart server.
