### ISSUE TITLE
[Feature] Option To Add A Direct Link To Metadata Page

### ISSUE THREAD

**Issue by seniorm0ment** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#27]
Suggesting a toggleable option to have Phoenix add a direct link to the page that it fetched the metadata for each item-at the bottom of the overview.

For example, a link to the JAVLibrary page, a link to the PornHub page, etc.

**Comment by DirtyRacer1337** [comment]
Already tried to do that at beginning. I'm not allowed just add url to metadata. Maybe if I'm create additional ExternalId to storage url. I'll think about it.
