### ISSUE TITLE
Plugin does not work in Jellyfin 10.9.2

### ISSUE THREAD

**Issue by ComprehensiveLuck125** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#272]
**Describe the bug**
It seems that plugin 2.7.0.47 stopped working for Jellyfin 10.9. Could you kindly release fix and bump versions up?

**Include**
1. Jellyfin 10.9.2

**Comment by wongsanchez** [comment]
I have this working in Jellyfin 10.9.6, what exactly isn't working for you?

**Comment by pprivately** [comment]
Oh well, it could be me / my Jellyfin installation when I am thinking more and take into consideration your comment.
For some reason JF 10.9.6 (now) is not pulling anymore anything from AdultDvd (normally I used flareresolver and in search was entering AdultDVD - 123456 (then it pulled metadata and images well. Do you know how to reset plugin folder completely in Jellyfin? Is it somewhere kept in host filesystem (I am running Jellyfin dockerized)?
I have pretty large metadata database, will have to backup before experimenting.

**Comment by SponkenDude** [comment]
Cannot get it to work either. Removed, and reinstalled. Same result.

MediaBrowser.Providers.Movies.MovieMetadataService: Error in PhoenixAdult
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Entities.PersonInfo.get_Type()'.
