### ISSUE TITLE
PAhelper/PhoenixAdult.bundle Deleted

### ISSUE THREAD

**Issue by bigbadwolfie** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#29]
Is there a new base repository for the Plex bundle? If not I think you should make https://github.com/DirtyRacer1337/PhoenixAdult.bundle the base repo as you contribute the most. Also would help to turn on issues in that repo.

**Comment by MajesticMaerlyn** [comment]
I think this is the same base, but now run by DR:
- https://github.com/DirtyRacer1337/PhoenixAdult.bundle

@DirtyRacer1337  - Correct me if I am wrong :)

**Comment by DirtyRacer1337** [comment]
I don't know what's happened, looks like PAhelper was deleted. I turned on issues and discussions.
