### ISSUE TITLE
[Feature] Optional Directory Exclusion Specification

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#35]
I'm unsure how much permission plugins can get, but if it is possible it would be nice to be able to specify directories that you want the plugin to **_completely_**  ignore (don't try to fetch, or read anything, just skip). The directory specified would of course also apply to all subdirectories and files, so absolutely nothing in that root directory is attempted.

This is something I hope jellyfin adds natively in the future, but it's not available now and I haven't heard any word on it.
It would be nice if it could be added to the plugin as an option.

**Comment by DirtyRacer1337** [comment]
That's be should do by Jellyfin/Emby. Plugin don't have access to file, only to that data

```csharp
namespace MediaBrowser.Controller.Providers
{
    public class ItemLookupInfo : IHasProviderIds
    {
        public ItemLookupInfo();

        public string Name { get; set; }
        public string MetadataLanguage { get; set; }
        public string MetadataCountryCode { get; set; }
        public ProviderIdDictionary ProviderIds { get; set; }
        public int? Year { get; set; }
        public int? IndexNumber { get; set; }
        public int? ParentIndexNumber { get; set; }
        public DateTimeOffset? PremiereDate { get; set; }
        public bool IsAutomated { get; set; }
        public bool EnableAdultMetadata { get; set; }
    }
}
```

**Comment by grravity** [comment]
Alright, guess I'll have to wait on file directory specification.

Could some kind of regex filter be added, that filters out everything with a certain name? It would act the same as I originally suggested, but just using the Name string?
For example just use regex to skip over all videos with "Test" in the name?

**Comment by DirtyRacer1337** [comment]
I don't understand how it helps and why do you need it. Can you give me example?

**Comment by grravity** [comment]
It would allow you to place an entire directory into a library, turn on jellyfinadult plugin, but have it skip over files you don't want being fetched or attempted. You could just split the files into two libraries, but this isn't entirely the best solution.

So for a super generic example, say I combined all my movies and music into one folder, then before each movie title I put "Movie -", and music "Music -".
If I used a regex option to select every filename that starts wjth "Music -", The regex elimination would basically make Phoenix Adult plugin completely skip over anything starting with "Music -" and ignore metadata for that. It wouldn't even attempt to fetch it ideally, it wouldn't make a query to the internet, nothing.

I get this seems niche, so it's understandable if you don't want to implement it. I was just trying to consider an alternative solution to my original idea of not being able to just tell plugins to ignore a folder within a library. That would be easier, but as you stated it's not possible because plugins don't have access to files/folders.

**Comment by DirtyRacer1337** [comment]
If the name starts with `Movie` or` Music`, the plugin won't find anything. The name should start with the name of the site.

Plugin should work only with movie.
Plugin use internet only if site was matched and contains search query.

I'm still not understand.

**Comment by grravity** [comment]
Those were just examples, but ok so you state

>Plugin use internet only if site was matched and contains search query.

That's understandable, so it queries the local list of sites, if it finds something it only uses the internet after it matches? Makes sense. However is there not a possibility for false positives?

**Comment by DirtyRacer1337** [comment]
Every request logged in `Debug` logs, like 
```
PhoenixAdult.Provider: Requesting GET "https://api.github.com/repos/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/contents/data"
```

You can enable debug logs by adding `"PhoenixAdult": "Debug"` in `logging.default.json`

```json
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning",
                "PhoenixAdult": "Debug"
            }
        },
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] [{ThreadId,3}] {SourceContext}: {Message:lj}{NewLine}{Exception}"
                }
            },
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "File",
                            "Args": {
                                "path": "%JELLYFIN_LOG_DIR%//log_.log",
                                "rollingInterval": "Day",
                                "retainedFileCountLimit": 3,
                                "rollOnFileSizeLimit": true,
                                "fileSizeLimitBytes": 100000000,
                                "outputTemplate": "[{Timestamp:HH:mm:ss.fff}] [{Level:u3}] [{ThreadId,3}] {SourceContext}: {Message}{NewLine}{Exception}"
                            }
                        }
                    ]
                }
            }
        ],
        "Enrich": [ "FromLogContext", "WithThreadId" ]
    }
}

```
