### ISSUE TITLE
almost 90% videos not identified automatically 

### ISSUE THREAD

**Issue by mukalaaa** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#4]
Hello @DirtyRacer1337 

I tested your plugin after you helped me set it up. the test was performed with 2 brazzers scenes and it worked perfectly. 

Now, I wanted to test it with almost 1700 brazzers scenes but I came across something strange !!

it identified few scenes, less than 10% of the entire library, as for the rest it get the scenes names correctly but no posters and no descriptions, no dates ...nothing !! 

I tried to identify the scenes manually and i just type in (brazzers - Scene name) and it finds it no problem. but as you know it is very hard to identify 1700 scenes manually !!

Please have a look at the attached photo to understand what I mean 

I also attached the jellyfin logs, it might give you insight on what is going on

Thanks a lot 
![jellyfin screenshot](https://user-images.githubusercontent.com/55691088/83776578-04401a00-a691-11ea-8683-b8fc2d7c0698.PNG)
[jellyfin logs.txt](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/4731038/jellyfin.logs.txt)

**Comment by DirtyRacer1337** [comment]
I see lots of error from `Screen Grabber`, it's in advanced settings of library, try to disable it. I tested it right now, it's not so much scenes like yours, but I got no errors.

**Comment by mukalaaa** [comment]
That is so strange because screen grabber is disabled !! 
I just checked it again now, and I was right, it is disabled!!

**Comment by mukalaaa** [comment]
Ok, I think I am closer to the problem than the solution 

So I decided to leave brazzers library now and try fakehub 

I have a file which is named as 

FakeCop 15.08.17 Jasmine

This file is identified automatically using PLEX. But, when I try, the jellyfin plugin, it never gets identified!! not even when I try to identify it manually. I even tried changing the file name from 
FakeCop 15.08.17 Jasmine   to  FakeCop 2015-08-17 Jasmine

I believe this is similar to the problem with brazzers library which i mentioned above. similar in terms, what we know is working with plex does not mean it would work the same way with jellyfin 

I also tested this with naughty america library, most of them were identified but the problem was if i have 5 scenes for actor X...then it identity the all of the 5 scenes as one scene, duplicates !!

**Comment by mukalaaa** [comment]
here is 2 photos to show you the difference between plex and jellyfin using the Phoenixadult plugin 

![plex identifying process](https://user-images.githubusercontent.com/55691088/83862911-47e76200-a72b-11ea-9942-ae74f59ef3fc.PNG)
![jellyfin identifying process](https://user-images.githubusercontent.com/55691088/83862930-503f9d00-a72b-11ea-8590-e34fba893563.PNG)

same file, same naming structure... in plex it is identified automatically, but in jellyfin it does not get identified automatically and when i tried to identify it manually, still the same, no results !!

**Comment by DirtyRacer1337** [comment]
Whats under `Media info` of this file, I don't see sitename and did it have `PhoenixAdult Id` it's in `Edit metadata`.
I fixed `FakeCop` search, you can match it now.
Naughty america is problem site, I'm sure plex can't match it too, better use sceneID matching.

**Comment by mukalaaa** [comment]
16.10.20.kimmie.fox is the folder name 
the file inside that folder does have the site name    faketaxi.16.10.20.kimmie.fox

FakeCop was just an example I used.... all FakeHub site such as fakecop, faketaxi, fakedrivingschool...etc are not being identified 

naughty america works well enough on plex, I can share a screenshot if you like

**Comment by DirtyRacer1337** [comment]
I wanna see screenshot of `Media info` and see waths iside of `PhoenixAdult Id`.
As I said, I fixed all `network1`.
I sure `naughty america` works bad like on plex, they identical. Send me screenshot, I wanna test it.

**Comment by mukalaaa** [comment]
if they are not identified the PhoenixAdult Id is empty 
only identified videos have PhoenixAdult Id
so i am not sure a screenshot will help here, unless you want a screenshot of an identified scene


here is the a screenshot of my naughty america library on plex, it has 683 scenes almost 99% identified correctly using sitename-date-actors, I hope that helps 
![naughty america at plex](https://user-images.githubusercontent.com/55691088/83877274-eaf7a600-a742-11ea-9e7a-782698a70f62.PNG)

**Comment by DirtyRacer1337** [comment]
I mean try match it right now. Ans show screenshot of `Media info`

**Comment by mukalaaa** [comment]
Now, looking at all those issues regarding brazzers or naughty america 

Do you think i should make the folder name similar to the files inside them? 

my current filing structure for example 

[2015-08-17 Jasmine]  FOLDER
    - FakeCop 2015-08-17 Jasmine.mp4 FILE

This structure works fine on plex but not jellyfin 

should i rename the folder from 2015-08-17 Jasmine to FakeCop 2015-08-17 Jasmine?

**Comment by mukalaaa** [comment]
by the way you said you fixed fakehub search but the code still says it was updates 3 days ago, shall I go ahead and download it?

**Comment by DirtyRacer1337** [comment]
Check commits

**Comment by mukalaaa** [comment]
ok i got brazzers working now, all i needed to do is change folder name to be similar to the file name 

we are still facing issues with fake hub but i am opening a new issue separate to make track king things easier, I hope you dont mind
