### ISSUE TITLE
Adulttime sites no longer work

### ISSUE THREAD

**Issue by emptyellipsis** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#46]
This is probably because of the site redesign, I'm not sure if there's a way to pull metadata anymore as all previews and tours are behind registration.

**Comment by DirtyRacer1337** [comment]
Logs, examples?

**Comment by DirtyRacer1337** [comment]
Found one error, probably fixed e1f2d3b207af82a8f15de359a680ab962d37c7cc
