### ISSUE TITLE
[enhancement] Create collections based on site name?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#54]
Could the plugin auto-create and manage collections based on the site name?

**Comment by DirtyRacer1337** [comment]
Added in b59a954d26d18a27a7ce55344a71ec2ced5b86de

**Comment by PAHelper2** [comment]
That's awesome!  Thank you!  Will it go through all existing videos and add them?  How do I use it?

**Comment by DirtyRacer1337** [comment]
Available in [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly), `Add Collection` task.
