### ISSUE TITLE
[enhancement] Sub-site on new collections feature?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#55]
Hi!  Thanks for adding the new 'Add to collections' scheduled task.  I'm testing it now, and it works great. 

One question: would it be possible to get the sub-site added as a separate collection also?  For example, right now all my Kink.com videos end up in a Kink collection.  Could we also have separate collections its sub-sites like 'Sex & Submission', 'The Upper Floor', 'Families Tied', etc?

Thanks again!

**Comment by DirtyRacer1337** [comment]
Added in 87b70e9d4775648c2ca86480f09e687d645a6f2c

But you have to update metadata (collection based on studio field), images would be not loaded, so it's should be fast.

**Comment by PAHelper2** [comment]
Thanks so much!  I'll test the next nightly.
