### ISSUE TITLE
how do we get brazzers with scene ID to be identified ?

### ISSUE THREAD

**Issue by mukalaaa** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#6]
I have the following brazzers scenes with scene ID's but they never get identified, not even manually 
what am I doing wrong in terms of naming? can you test it please 

brazzers - 74371 - 7 minutes in heaven
brazzers - 118161 - 60 minutes Of Anal!
brazzers - 2412377 - 1 800 phone sex line 10

**Comment by DirtyRacer1337** [comment]
brazzers - 74371 - 7 minutes in heaven
Looks like wrong sceneid, 6763 correct one

brazzers - 118161 - 60 minutes Of Anal!
correct: 5584

brazzers - 2412377 - 1 800 phone sex line 10
this one works correct
