### ISSUE TITLE
AdultDVDEmpire support?  How to name files?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#67]
Hi, I noticed that support for full length movies from AdultDVDEmpire was added.  How should I name the movies to properly lookup metadata from that site?  Thanks!

**Comment by DirtyRacer1337** [comment]
If site unknown it's going to MetadataAPI (If it's setted up) or it would be `JAV` if javcode would be found, but you can set `DefaultSiteName` in setting then it's going to that you set

**Comment by DirtyRacer1337** [comment]
Or try new feature, 734a87e185e731797335dfee7a638fda7ddcfbba
You can put you files in folder `AdultDVDEmpire` and it would be work, set `Use FilePath for matching`
