### ISSUE TITLE
Option to make requests through a proxy.

### ISSUE THREAD

**Issue by anon-127** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#74]
A lot of sites this plugin scrapes are banned in my location.It would be cool if there was a proxy field in the settings.

I don't want to use proxy on jellyfin as a whole as it will slow things down a lot.

**Comment by DirtyRacer1337** [comment]
I added Socks proxy support in 003481dc663d088011fea0cc740bc22250cd3ac5, should be working, check [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly). Server restart required for accepting proxy.

**Comment by blackCauldron7** [comment]
Can you add http proxy i have http proxy on my home machine.

**Comment by anon-127** [comment]
http proxy supported?

**Comment by DirtyRacer1337** [comment]
probably don't supported

**Comment by anon-127** [comment]
can the support be added?

**Comment by DirtyRacer1337** [comment]
better use socks they universal, for http required two proxies for http and https, I don't want to deal with it
