### ISSUE TITLE
Emby Compatibility

### ISSUE THREAD

**Issue by sdy12318** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#8]
Can this plug-in also work for Emby?

**Comment by DirtyRacer1337** [comment]
This one not support emby, but I made a big first step to make it, moved all functionality to [PhoenixAdult.NET](https://github.com/DirtyRacer1337/PhoenixAdult.NET), just need to make emby metadata provider

**Comment by DirtyRacer1337** [comment]
Implemented [Emby.Plugins.PhoenixAdult](https://github.com/DirtyRacer1337/Emby.Plugins.PhoenixAdult)
