### ISSUE TITLE
Clips4Sale HTML selector not working

### ISSUE THREAD

**Issue by DeliciousOppai** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#82]
**Describe the bug**
Clips4Sale does not seem to return any results, because the HTML selector does not return any elements.

**Include**
1. Jellyfin
2. Plugin Version 2.6.2.46
3. Clips4Sale

The HTML selector at https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/blob/master/Jellyfin.Plugin.PhoenixAdult/Sites/SiteClips4Sale.cs#L45 seems to refer to the inner section elements with class 'p-0' . When checking actual search results, it seems that the class that gets return in my case is 'p-2'. Regardless, it seems that this number might change, so it might be better to check for another class (or discard it entirely, there don't seem to be any other section elements).

When trying with this selector in my browser console, I get list of section elements as expected: $('div.clipWrapper section.studio-list-item-wrapper') .

**Comment by DirtyRacer1337** [comment]
Fixed 09ebf1be03441da0dc9f764968ee84baedf1fcc1
