### ISSUE TITLE
PornHub does not result in any result

### ISSUE THREAD

**Issue by roflolorz** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#84]
Hello, I am using Emby but there seems to be no results when searching for vids in pornhub. No matter I search for the title or the video link, no result shows up. Are there any settings need to be modified before it works?

**Comment by DirtyRacer1337** [comment]
Fixed in 05bc6abe9221f9c96fc109eff625738922782625

**Comment by roflolorz** [comment]
Any chance to make it work if I have a premium account?

**Comment by DirtyRacer1337** [comment]
I don't have a plans for it
