### ISSUE TITLE
Making this easily work on all platforms easily even with new versions of Jellyfin including my Debian 10 Linux

### ISSUE THREAD

**Issue by sponix** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#9]
From #jellyfin on irc.freenode.net

sparky[m]> point them to our plugin blog post too sponix. https://jellyfin.org/posts/plugin-updates/ can now add 3rd party repos and he can host one via github. can then use the normal plugin management method for their plugin

Thanks in advance,
sponix

**Comment by DirtyRacer1337** [comment]
Implemened
