### ISSUE TITLE
Some of the covers of pornhub turned into corn

### ISSUE THREAD

**Issue by fqscfqj** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#91]
**Describe the bug**

**Include**
1. Jellyfin10.7.6
2. Plugin 2.6.2.46
3. Scene URL https://cn.pornhub.com/view_video.php?viewkey=Ph608834456a160
4. File Name pornhub.Ph608834456a160
5. Log File
![屏幕截图 2021-09-01 010710](https://user-images.githubusercontent.com/68098251/131546412-7286aefc-ca55-4ab6-8dd6-d03f64e1c592.png)

**Comment by DirtyRacer1337** [comment]
Maybe it's cache, try to disable it in settings and restart server

**Comment by henry-1987** [comment]
I was having issues tracking down the same problem and was debugging for days. Tried a POST request instead of GET and I got the right video. Finally. Thank you!

**Comment by fqscfqj** [comment]
It's done
