### ISSUE TITLE
Gloryhole.com (Dogfart) - Many scenes  get incorrectly labeled as a particular scene - Ironically that scene gets labeled something else

### ISSUE THREAD

**Issue by C84186** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#95]
**Describe the bug**

A lot of gloryhole scenes get mislabeled as:
> Dee Williams & Kali Roses from GloryHole.com

Ironically, the actual scene:
`GloryHole.21.08.07.Dee.Williams.And.Kali.Roses.XXX.480p.MP4-XXX/gloryhole.21.08.07.dee.williams.and.kali.roses.mp4`

Gets mislabeled as
> Brandi Love from GloryHole.Com

1. Jellyfin Version 10.7.5
2. Plugin Version: 2.6.1.45
# Scene Urls

- https://www.dogfartnetwork.com/tour/sites/GloryHole/brandi_love/?nats=MTY4MzkuMy4yMy4yMy4zLjAuMC4wLjA
- https://www.dogfartnetwork.com/tour/sites/GloryHole/dee_williams_kali_roses/?nats=MTY4MzkuMy4yMy4yMy4zLjAuMC4wLjA
- https://www.dogfartnetwork.com/tour/sites/GloryHole/alex_coal_alura_jenson/?nats=MTY4MzkuMy4yMy4yMy4zLjAuMC4wLjA
- https://www.dogfartnetwork.com/tour/sites/Gloryhole-Initiations/crystal_cooper_kaiya_rose/?nats=MTY4MzkuMy4yMy4yMy4zLjAuMC4wLjA
- https://www.dogfartnetwork.com/tour/sites/GloryHole/danielle_derek/?nats=MC4wLjIzLjIzLjAuMC4wLjAuMA

# Files:

## Files that get mislabeled as Dee Williams & Kali Roses:

- GloryHoleSecrets.21.07.30.Kaitlyn.Katsaros.First.Cum.Closet.XXX.SD.MP4-KLEENEX/GloryHoleSecrets.21.07.30.Kaitlyn.Katsaros.First.Cum.Closet.XXX.SD.MP4-KLEENEX.mp4
- GloryHole.21.06.12.Alex.Coal.And.Alura.Jenson.XXX.480p.MP4-XXX/gloryhole.21.06.12.alex.coal.and.alura.jenson.mp4
- [BlacksOnCougars] Alura Jenson and Dee Williams (27.09.2017) rq.mp4
- GloryHoleSecrets.19.06.14.Aubrey.Black.First.Glory.Hole.XXX.1080p.MP4-KTR[rarbg]/gloryholesecrets.19.06.14.aubrey.black.first.glory.hole.mp4
- GloryHoleInitiations - 2020/11/26 Crystal Cooper And Kaiya Rose/gloryhol-initiations.20.11.26.crystal.cooper.and.kaiya.rose.mp4
- GloryHole.19.01.28.Danielle.Derek.XXX.SD.MP4-KLEENEX/GloryHole.19.01.28.Danielle.Derek.XXX.SD.MP4-KLEENEX.mp4

## Files that get mislabeled as Brandi Love from GloryHole.Com

GloryHole.21.08.07.Dee.Williams.And.Kali.Roses.XXX.480p.MP4-XXX/gloryhole.21.08.07.dee.williams.and.kali.roses.mp4

5. Log File

Which log file?

**Comment by DirtyRacer1337** [comment]
Use one actor name for search, site have bad search functionality
https://www.dogfartnetwork.com/tour/search.php?search=Dee%20Williams%20And%20Kali%20Roses

**Comment by C84186** [comment]
> Use one actor name for search, site have bad search functionality
It sure does - but how can i make PhoenixAdult do that?
> https://www.dogfartnetwork.com/tour/search.php?search=Dee%20Williams%20And%20Kali%20Roses

**Comment by DirtyRacer1337** [comment]
> > Use one actor name for search, site have bad search functionality
> 
> It sure does - but how can i make PhoenixAdult do that?

rename file or use identify in jellyfin
