### ISSUE TITLE
Sites under NetworkPorndoe is not loading

### ISSUE THREAD

**Issue by kennyluk** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#99]
**Describe the bug**
Searches under networkporndoe is not going through because letsdoeit.com is putting up an age check page when you send the q= query through.

**Include**
1. Jellyfin 10.7.7
2. Nightly

**Comment by DirtyRacer1337** [comment]
Fixed in c6addc13949e29881fae5cf052cdf5a5df16636b
